###
POST http://localhost:3003/api/v1/auth/login HTTP/1.1
content-type: application/json

{
   "password": "1234",
   "email" :"a@a"
}

###
POST http://localhost:3003/api/v1/auth/register HTTP/1.1
content-type: application/json

{
   "password": "1234",
   "email" :"c@c"
}
